name: 'Apply the sonar exclusion properties and report files being excluded'
description: "An action to apply the sonar exclusion properties and report files being excluded"
author: 'newlight77'

branding:
  icon: 'anchor'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/main/index.js'
