name: 'Select sonar properties rules according to the project stack before code analysis'
description: "An action to select sonar properties"
author: 'newlight77'

branding:
  icon: 'anchor'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/main/index.js'
