name: 'Run code analysis with sonar (coverage and static code analysis)'
description: "An action to run the code analysis with sonar (coverage and static code analysis)"

inputs:
  sonar-token:
    description: a token to publish metrics
    required: true
  slack-bot-token:
    description: a token to sent notification on slack
    required: true
  project-stack:
    description: the project stack (node | next | react)
    required: true


runs:
  using: "composite"
  steps:
    - name: Use variables
      run: |
        echo "SONAR_TOKEN : $SONAR_TOKEN"
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      shell: bash

    - name: checkout 🛎️
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: 'Download coverage from multiple test suites'
      id: download-all-coverage
      uses: newlight77/github-actions/.github/actions/download-all-coverage@main
      with:
        with-unit-test: ${{ inputs.with-unit-test }}
        with-feature-test: ${{ inputs.with-feature-test }}

    - name: 'Merge coverage from multiple test suites'
      id: merge-coverage
      uses: newlight77/github-actions/.github/actions/merge-coverage@main
      with:
        with-unit-test: ${{ inputs.with-unit-test }}
        with-feature-test: ${{ inputs.with-feature-test }}

    - name: 'Normalize sonar properties'
      id: normalize-sonar-properties
      uses: newlight77/github-actions/.github/actions/sonar-properties-normalizer@main
      with:
        project-stack: ${{ inputs.project-stack }}

    - name: 'Sonar exclusions report'
      id: sonar-exclusions-report
      uses: newlight77/github-actions/.github/actions/sonar-exclusions-report@main

    - name: '[bypass quality-gate], if set'
      id: bypass-quality-gate
      uses: newlight77/github-actions/.github/actions/sonarcloud-quality-gate-switch@main
      with:
        sonarcloud-token: ${{ inputs.sonar-token }}
        organization: "newlight77"
        project-key: "newlight77_${{ github.event.repository.name }}"
        tmp-gate-id: "100003"
        pr-head-commit: ${{ github.event.pull_request.head.sha }}

    - name: run sonarcloud action
      uses: SonarSource/sonarcloud-github-action@v2.0.0
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}

    - name: slack notification using bypassing if bypass-quality-gate
      if: ${{ steps.bypass-quality-gate.outputs.bypassed == 'true' }}
      uses: newlight77/github-actions/.github/actions/slack-notifier@main
      with:
        slack-bot-token: ${{ inputs.slack-bot-token }}
        channel-id: "C05UA1LUW1H" #ci
        pretext: "Quality Gate bypassed"
