name: 'Select sonar properties rules according to the project stack before code analysis'
description: "An action to select sonar properties"
author: 'thefork'

inputs:
  project-stack:
    description: the project stack (node | next | react | java | android | ios)
    required: true
    type: string
  sonar-properties-path:
    description: the project stack (node | next | react | java | android | ios)
    required: true
    type: string


branding:
  icon: 'anchor'
  color: 'blue'

runs:
  using: 'node16'
  main: 'dist/main/index.js'
